CREATE TABLE IF NOT EXISTS students (
  id int NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  mark TINYINT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci